Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  config.vm.define "controller" do |controller|
    controller.vm.provider "virtualbox" do |vb_c|
      vb_c.memory = 2048
      vb_c.cpus = 2
    end
    controller.vm.hostname = "ansiblecontroller"
    controller.vm.network "private_network", ip: "192.168.33.10"
  end
  
  config.vm.define "target1" do |target1|
    target1.vm.provider "virtualbox" do |vb_t1|
      vb_t1.memory = 1024
      vb_t1.cpus = 1
    end
    target1.vm.hostname = "target1"
    target1.vm.network "private_network", ip: "192.168.33.11"
  end
  
  config.vm.define "target2" do |target2|
    target2.vm.provider "virtualbox" do |vb_t2|
      vb_t2.memory = 1024
      vb_t2.cpus = 1
    end
    target2.vm.hostname = "target2"
    target2.vm.network "private_network", ip: "192.168.33.12"
  end

end